---
apiVersion: v1
kind: Pod
metadata:
  name: dataaccess-wp-content
  namespace: wordpress
spec:
  containers:
  - name: alpine
    image: alpine:latest
    command: ['tail', '-f', '/dev/null']
    volumeMounts:
    - name: wordpress-production-wp-content
      mountPath: /data
  volumes:
  - name: wordpress-production-wp-content
    persistentVolumeClaim:
      claimName: wordpress-production-wp-content
